### ISSUE TITLE
onRefresh not triggered when items fit in viewport

### ISSUE THREAD

**Issue by brysem** [hyochan/flat_list#5]
**Description**

First of all amazing package! Love the functionality. I am running into one small issue though.

The FlatList onRefresh is not fired when the list is smaller than the viewport of the screen.
As soon as the list has more items than fits inside the viewport, the onRefresh behavior works as expected.

**Expected Behavior**

I expect to see the RefreshIndicator and the code inside onRefresh executed.

**Environment:**

- flat_list: ^0.1.13
- flutter: sdk: '>=2.19.4 <3.0.0'
- Platforms (iOS, Android, emulator, simulator, device): iOS simulator

**To Reproduce**

1. Create a flatlist with 1 item that fits entirely within the viewport.
2. Add an onRefresh callback with a print.
3. Try dragging down. It should not be possible.
4. The onRefresh callback is not called.

**Comment by hyochan** [comment]
Hi @brysem ! Thanks for the issue.
Could you kindly push a reproducible example as `FlatList Example5` after forking the repository?

<img width="990" alt="Screenshot 2023-03-15 at 11 57 55 PM" src="https://user-images.githubusercontent.com/27461460/225349825-612676f7-2d0f-4347-9a67-ae92617ab9c9.png">

I'll try to investigate the problem after that.

**Comment by brysem** [comment]
Thanks for the quick reply.

I created an example 6 in my fork. https://github.com/brysem/flat_list/commit/1c3499d468aa3aea461852f682b0d6ea0dc7ae16
![image](https://user-images.githubusercontent.com/2829285/226097711-4dcde15a-16ee-47c5-9084-3631223bf730.png)

Observations:
1. onRefresh does not work when the total amount of items all fit inside the viewport OR the list is empty.
2. onEndReached does not work when the total amount of items all fit inside the viewport.

If I can help anymore

**Comment by brysem** [comment]
I decided to have a go at fixing the issue myself. Please see https://github.com/hyochan/flat_list/pull/6
I apologize for the auto formatting.
